require 'omniauth-geekpark/version'
require 'omniauth-geekpark/helper'
require 'omniauth-oauth2'
require 'patch/omniauth-oauth2'
require 'omniauth/strategies/geekpark'
require 'omniauth/strategies/wechat'
require 'omniauth/strategies/wechat_service'
require 'omniauth/strategies/weibo'
